wagtail/contrib/forms/urls.py
from django.urls import path

from wagtail.contrib.forms.views import (
    DeleteSubmissionsView,
    FormPagesListView,
    get_submissions_list_view,
)

app_name = "wagtailforms"
urlpatterns = [
    path("", FormPagesListView.as_view(), name="index"),
    path(
        "results/", FormPagesListView.as_view(results_only=True), name="index_results"
    ),
    path(
        "submissions/<int:page_id>/", get_submissions_list_view, name="list_submissions"
    ),
    path(
        "submissions/<int:page_id>/delete/",
        DeleteSubmissionsView.as_view(),
        name="delete_submissions",
    ),
]

wagtail/contrib/forms/templates/wagtailforms/confirm_delete.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans trimmed with title=page.title %}Delete form data {{ title }}{% endblocktrans %}{% endblock %}
{% block bodyclass %}menu-explorer{% endblock %}

{% block content %}
    {% trans "Delete form data" as del_str %}
    {% include "wagtailadmin/shared/header.html" with title=del_str subtitle=page.title icon="doc-empty-inverse" %}

    <div class="nice-padding">
        <p>
            {% blocktrans trimmed count counter=submissions.count %}
                Are you sure you want to delete this form submission?
            {% plural %}
                Are you sure you want to delete these form submissions?
            {% endblocktrans %}
        </p>
        <form action="{% url 'wagtailforms:delete_submissions' page.id %}?{{ request.GET.urlencode }}" method="POST">
            {% csrf_token %}
            <input type="submit" value="{% trans 'Delete' %}" class="button serious">
        </form>
    </div>
{% endblock %}

wagtail/contrib/forms/templates/wagtailforms/content_type_column.html
<td {% if column.classname %}class="{{ column.classname }}"{% endif %}>
    <small><a href="{{ url }}" class="nolink">{{ value.name |capfirst }} ({{ value.app_label }}.{{ value.model }})</a></small>
</td>

wagtail/contrib/forms/templates/wagtailforms/index.html
{% extends "wagtailadmin/generic/index.html" %}

wagtail/contrib/forms/templates/wagtailforms/index_results.html
{% extends "wagtailadmin/generic/index_results.html" %}

wagtail/contrib/forms/templates/wagtailforms/list_submissions.html
{% load i18n %}
<div class="w-overflow-auto">
    <table class="listing" data-controller="w-bulk" data-w-bulk-action-inactive-class="w-invisible">
        <col />
        <col />
        <col />
        <thead>
            <tr>
                <th colspan="{{ data_headings|length|add:1 }}">
                    <button class="button no w-invisible" data-w-bulk-target="action">{% trans "Delete selected submissions" %}</button>
                </th>
            </tr>
            <tr>
                <th><input type="checkbox" data-action="w-bulk#toggleAll" data-w-bulk-target="all" /></th>
                {% for heading in data_headings %}
                    <th id="{{ heading.name }}" class="{% if heading.order %}ordered icon {% if heading.order == 'ascending' %}icon-arrow-up-after{% else %}icon-arrow-down-after{% endif %}{% endif %}">
                        {% if heading.order %}<a href="?order_by={% if heading.order == 'ascending' %}-{% endif %}{{ heading.name }}">{{ heading.label }}</a>{% else %}{{ heading.label }}{% endif %}
                    </th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for row in data_rows %}
                <tr>
                    <td>
                        <input type="checkbox" name="selected-submissions" class="select-submission" value="{{ row.model_id }}" data-action="w-bulk#toggle" data-w-bulk-target="item" />
                    </td>
                    {% for cell in row.fields %}
                        <td>
                            {{ cell }}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

wagtail/contrib/forms/templates/wagtailforms/submissions_index.html
{% extends "wagtailadmin/base.html" %}
{% load i18n wagtailadmin_tags %}
{% block titletag %}{% blocktrans trimmed with form_title=form_page.title|capfirst %}Submissions of {{ form_title }}{% endblocktrans %}{% endblock %}
{% block extra_js %}
    {{ block.super }}

    <script>
        $.fn.datetimepicker.defaults.i18n.wagtail_custom_locale = {
            months: wagtailConfig.STRINGS.MONTHS,
            dayOfWeek: wagtailConfig.STRINGS.WEEKDAYS,
            dayOfWeekShort: wagtailConfig.STRINGS.WEEKDAYS_SHORT,
        }
        $.datetimepicker.setLocale('wagtail_custom_locale');

        $(function() {
            $('#id_date_from').datetimepicker({
                timepicker: false,
                format: 'Y-m-d',
            });
            $('#id_date_to').datetimepicker({
                timepicker: false,
                format: 'Y-m-d',
            });
        });
    </script>
{% endblock %}
{% block content %}
    {% fragment as form_actions %}
        {% include view.export_buttons_template_name %}
    {% endfragment %}

    {% include "wagtailadmin/shared/header.html" with classname="w-header--no-border" title=page_title subtitle=form_page.title|capfirst icon="form" merged=1 extra_actions=form_actions %}

    <div class="report filterable">
        <div class="report__results w-overflow-y-hidden w-overflow-x-scroll w-pb-6">
            {% if submissions %}
                <form action="{% url 'wagtailforms:delete_submissions' form_page.id %}" method="get">
                    {% include "wagtailforms/list_submissions.html" %}
                    {% include "wagtailadmin/shared/pagination_nav.html" with items=page_obj %}
                </form>
            {% else %}
                <p class="no-results-message">{% blocktrans trimmed with title=form_page.title %}There have been no submissions of the '{{ title }}' form.{% endblocktrans %}</p>
            {% endif %}
        </div>
        <div class="filterable__filters">
            <h2>{% trans 'Filter' %}</h2>
            <form action="" method="get" novalidate>
                <button
                    class="button button-longrunning"
                    type="submit"
                    data-controller="w-progress"
                    data-action="w-progress#activate"
                >
                    {% icon name="spinner" %}{% trans 'Apply filters' %}
                </button>
                {% for field in select_date_form %}
                    <li>
                        {% formattedfield field %}
                    </li>
                {% endfor %}
            </form>
        </div>
    </div>
{% endblock %}